baseURL = ""
title = "af-FAB-le"
copyright = "CCBY-4.0 Clara Rigaud and Yvonne Jansen"
paginate = 0
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
googleAnalytics = "UA-XXXX"
DisqusShortname = ""
theme = "chunky-poster"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "Capush"
    name = "Capush"
    url = "/capush/"
    weight = 3

[taxonomies]
category = "categories"
tag = "tags"
series = "series"
author = "authors"

[params]
  author = "Clara Rigaud & Yvonne Jansen"
  description = "A summary of the outcomes of the af-FAB-le project."
  homepageImage = "/images/logo_affable.jpg"
  dateFormat = "January 2, 2006"
  share = true
  showLanguageSwitcher = false

  # Custom CSS and JS. Relative to /static/css and /static/js respectively.
  customCSS = ["style.css"]
  customJS = []


[markup]
  [markup.highlight]
    codeFences = false

